# A1 starter deck for app/tools/italian.py, introduced in this order: the
# phrases needed to get through a first conversation come first, then
# numbers, time, food, travel, core verbs, and a little business Italian.
# (italian, english, topic)
DECK: list[tuple[str, str, str]] = [
    # Greetings and courtesy
    ("ciao", "hi / bye (informal)", "greetings"),
    ("buongiorno", "good morning / good day", "greetings"),
    ("buonasera", "good evening", "greetings"),
    ("arrivederci", "goodbye", "greetings"),
    ("per favore", "please", "courtesy"),
    ("grazie", "thank you", "courtesy"),
    ("prego", "you're welcome", "courtesy"),
    ("scusi", "excuse me (formal)", "courtesy"),
    ("mi dispiace", "I'm sorry", "courtesy"),
    ("sì", "yes", "basics"),
    ("no", "no", "basics"),
    ("come stai?", "how are you? (informal)", "conversation"),
    ("come sta?", "how are you? (formal)", "conversation"),
    ("sto bene, grazie", "I'm well, thanks", "conversation"),
    ("mi chiamo Andrew", "my name is Andrew", "conversation"),
    ("come ti chiami?", "what's your name? (informal)", "conversation"),
    ("piacere", "nice to meet you", "conversation"),
    ("di dove sei?", "where are you from? (informal)", "conversation"),
    ("sono americano", "I'm American", "conversation"),
    ("parlo un po' di italiano", "I speak a little Italian", "conversation"),
    ("non capisco", "I don't understand", "conversation"),
    ("può ripetere, per favore?", "can you repeat, please? (formal)", "conversation"),
    ("parla inglese?", "do you speak English? (formal)", "conversation"),
    ("come si dice ...?", "how do you say ...?", "conversation"),
    # Numbers
    ("uno", "one", "numbers"),
    ("due", "two", "numbers"),
    ("tre", "three", "numbers"),
    ("quattro", "four", "numbers"),
    ("cinque", "five", "numbers"),
    ("sei", "six", "numbers"),
    ("sette", "seven", "numbers"),
    ("otto", "eight", "numbers"),
    ("nove", "nine", "numbers"),
    ("dieci", "ten", "numbers"),
    ("venti", "twenty", "numbers"),
    ("cento", "one hundred", "numbers"),
    # Time
    ("oggi", "today", "time"),
    ("domani", "tomorrow", "time"),
    ("ieri", "yesterday", "time"),
    ("adesso", "now", "time"),
    ("lunedì", "Monday", "time"),
    ("martedì", "Tuesday", "time"),
    ("mercoledì", "Wednesday", "time"),
    ("giovedì", "Thursday", "time"),
    ("venerdì", "Friday", "time"),
    ("sabato", "Saturday", "time"),
    ("domenica", "Sunday", "time"),
    ("che ore sono?", "what time is it?", "time"),
    ("la settimana", "the week", "time"),
    # Food and café
    ("un caffè, per favore", "a coffee, please", "food"),
    ("l'acqua", "water", "food"),
    ("il pane", "bread", "food"),
    ("il conto, per favore", "the check, please", "food"),
    ("vorrei ...", "I would like ...", "food"),
    ("quanto costa?", "how much does it cost?", "food"),
    ("buono", "good (tasty)", "food"),
    ("la colazione", "breakfast", "food"),
    ("il pranzo", "lunch", "food"),
    ("la cena", "dinner", "food"),
    # Travel and directions
    ("dov'è ...?", "where is ...?", "travel"),
    ("a destra", "to the right", "travel"),
    ("a sinistra", "to the left", "travel"),
    ("sempre dritto", "straight ahead", "travel"),
    ("la stazione", "the station", "travel"),
    ("l'aeroporto", "the airport", "travel"),
    ("il biglietto", "the ticket", "travel"),
    ("vicino", "near", "travel"),
    ("lontano", "far", "travel"),
    # Core verbs, present tense
    ("io sono", "I am (essere)", "verbs"),
    ("tu sei", "you are, informal (essere)", "verbs"),
    ("lui / lei è", "he / she is (essere)", "verbs"),
    ("noi siamo", "we are (essere)", "verbs"),
    ("io ho", "I have (avere)", "verbs"),
    ("tu hai", "you have, informal (avere)", "verbs"),
    ("lui / lei ha", "he / she has (avere)", "verbs"),
    ("noi abbiamo", "we have (avere)", "verbs"),
    ("io vado", "I go (andare)", "verbs"),
    ("io faccio", "I do / make (fare)", "verbs"),
    ("io voglio", "I want (volere)", "verbs"),
    ("io posso", "I can (potere)", "verbs"),
    ("io parlo", "I speak (parlare)", "verbs"),
    ("io lavoro", "I work (lavorare)", "verbs"),
    ("io studio", "I study (studiare)", "verbs"),
    # Questions
    ("chi?", "who?", "questions"),
    ("che cosa?", "what?", "questions"),
    ("quando?", "when?", "questions"),
    ("dove?", "where?", "questions"),
    ("perché?", "why? / because", "questions"),
    ("come?", "how?", "questions"),
    ("quanto?", "how much?", "questions"),
    # Business and school
    ("il lavoro", "work / the job", "business"),
    ("l'azienda", "the company", "business"),
    ("la riunione", "the meeting", "business"),
    ("il cliente", "the client", "business"),
    ("l'università", "the university", "business"),
    ("lo studente", "the student (male)", "business"),
    ("sono uno studente", "I am a student", "business"),
    ("ho una startup", "I have a startup", "business"),
    ("piacere di conoscerla", "pleased to meet you (formal)", "business"),
]
