import re
from collections.abc import Callable

from app.core.gemini import AllModelsExhausted, GeminiNotConfigured
from app.integrations.gemini_render import generate_image
from app.tools.notes import save_note

# Jarvis putting something on screen: an equation, worked steps, code, a
# file to download or an image, in its own window in the console
# (web/src/components/showcase/). It is for what should be LOOKED AT -
# chat text is plain and the voice cannot read out an integral - so the
# reply can point at the window instead of reciting it.
#
# Console channel only, like the console tool. Notes (kind text) are also
# saved to Drive as .txt files (app/tools/notes.py), to find again later.

KINDS = ["equation", "text", "code", "file", "image"]
MAX_CONTENT_CHARS = 60_000
# Text files only: everything here is written by the model as text.
FILE_TYPES = {
    "txt": "text/plain", "md": "text/markdown", "csv": "text/csv", "json": "application/json",
    "tex": "application/x-tex", "py": "text/x-python", "js": "text/javascript",
    "ts": "text/typescript", "html": "text/html", "css": "text/css", "scad": "text/plain",
    "yaml": "text/yaml", "yml": "text/yaml", "xml": "application/xml", "sql": "text/plain",
    "ics": "text/calendar", "svg": "image/svg+xml",
}

SHOWCASE_SCHEMA = {
    "type": "function",
    "function": {
        "name": "showcase",
        "description": (
            "Put something on Andrew's screen in a pop-up window, for anything better seen than "
            "heard or read as plain chat text. kind: equation (one LaTeX expression, displayed "
            "large), text (worked steps, notes or a list; plain lines, '- ' for bullets, inline "
            "math as $...$ and display math as $$...$$ in LaTeX; saved to his Drive as a .txt "
            "note he can find later), code (source with `language`), "
            "file (a text file he can download: give `filename` with its extension, and the full "
            "contents), image (generated by an image model from `image_prompt`; set from_camera "
            "to use the current camera frame as the reference, e.g. to redraw the board's "
            "diagram cleanly). Several calls make several windows."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "title": {"type": "string", "description": "Short window title."},
                "kind": {"type": "string", "enum": KINDS},
                "content": {
                    "type": "string",
                    "description": "equation: LaTeX. text: the text. code: the source. file: the file's contents.",
                },
                "caption": {"type": "string", "description": "Optional one-line note under it."},
                "language": {"type": "string", "description": "code: e.g. python, matlab, javascript."},
                "filename": {"type": "string", "description": "file: e.g. notes.md, data.csv."},
                "image_prompt": {"type": "string", "description": "image: what to draw, in detail."},
                "from_camera": {"type": "boolean", "description": "image: base it on the camera frame."},
            },
            "required": ["title", "kind"],
        },
    },
}

SHOWCASE_NOTE = (
    "SHOWCASE: you have a screen. When the answer is something to look at - an equation, a "
    "derivation or worked steps, code, a table of figures, a file, a picture - put it up with "
    "showcase rather than writing it into the chat, where math and code read badly and the voice "
    "cannot say them. Then keep the reply short and point at it (\"On screen, sir.\"), adding "
    "only what is worth saying aloud. Do not repeat the window's contents in the reply. Short "
    "plain answers still go in the chat as usual. If CONSOLE_STATE lists a window open, that is "
    "what he is looking at. Saying something is on screen does not put it there: never say "
    "\"on screen\" or \"in the window\" unless you called showcase in this same reply. Checked "
    "answers, marked questions and lists of results are things to look at - showcase them."
)


def _filename(raw: str) -> str | None:
    name = re.sub(r"[^\w.\- ]", "_", raw.strip())[:80].strip(". ")
    ext = name.rsplit(".", 1)[-1].lower() if "." in name else ""
    return name if ext in FILE_TYPES else None


def make_showcase(frame_b64: str | None, frame_type: str) -> Callable[[dict], dict]:
    """A showcase handler for this turn, holding the camera frame (if any)
    for an image drawn from the board."""

    def showcase(args: dict) -> dict:
        kind = args.get("kind")
        if kind not in KINDS:
            return {"ok": False, "error": f"kind must be one of {KINDS}"}
        title = str(args.get("title") or "").strip()[:80] or kind.title()
        caption = str(args.get("caption") or "").strip()[:300]
        content = str(args.get("content") or "")
        if len(content) > MAX_CONTENT_CHARS:
            return {"ok": False, "error": f"content is over {MAX_CONTENT_CHARS} characters"}
        item: dict = {"kind": kind, "title": title, "caption": caption}

        if kind in ("equation", "text", "code"):
            if not content.strip():
                return {"ok": False, "error": f"{kind} needs content"}
            item["content"] = content.strip()
            if kind == "code":
                item["language"] = str(args.get("language") or "").strip()[:20]
        elif kind == "file":
            name = _filename(str(args.get("filename") or ""))
            if not name:
                return {"ok": False, "error": f"filename needs one of these extensions: {sorted(FILE_TYPES)}"}
            if not content:
                return {"ok": False, "error": "file needs content"}
            item.update(content=content, filename=name, mime=FILE_TYPES[name.rsplit('.', 1)[1].lower()])
        else:
            prompt = str(args.get("image_prompt") or args.get("content") or "").strip()[:1500]
            if not prompt:
                return {"ok": False, "error": "image needs image_prompt"}
            reference = frame_b64 if args.get("from_camera") else None
            if args.get("from_camera") and not reference:
                return {"ok": False, "error": "The camera is off, so there is no frame to work from."}
            try:
                image = generate_image(prompt, reference, frame_type)
            except GeminiNotConfigured as exc:
                return {"ok": False, "error": str(exc)}
            except AllModelsExhausted as exc:
                return {"ok": False, "error": f"No image model would take it - {exc.detail()}"}
            except Exception as exc:  # noqa: BLE001 — say why, rather than failing the turn
                return {"ok": False, "error": f"Image generation failed: {exc}"}
            # image_data goes to the console only; the orchestrator strips it
            # from what the model and the logs see.
            item.update(image_data=image["image"], mime=image["mime"])
            if not caption and image["note"]:
                item["caption"] = image["note"][:300]

        note = "On his screen now, in its own window."
        if kind == "text":
            # A .txt in Drive as well as on screen. Saving is a bonus: if Drive
            # fails, the window still opens and the reply can say so.
            try:
                saved = save_note(title, item["content"])
                item.update(filename=saved["name"], mime="text/plain", drive_link=saved["link"])
                note += f" Saved to Drive as \"{saved['name']}\" in Jarvis Notes."
            except Exception as exc:  # noqa: BLE001
                item.update(filename=f"{title}.txt", mime="text/plain")
                note += f" Not saved to Drive: {exc}"
        return {"ok": True, "showcase": item, "note": note}

    return showcase


def state_line(state: dict | None) -> str | None:
    """What the showcase window is showing, for CONSOLE_STATE."""
    showing = (state or {}).get("showcase")
    if not isinstance(showing, dict):
        return None
    return f"Showcase window open: \"{str(showing.get('title'))[:80]}\" ({showing.get('kind')})."
